This file describes the  SLTRConfig
add from luckyshd
.. contents:: 
    :local: 
    :depth: 2


Methods(ISVCEncoder)
============================

structure for LTR configure


+--------------------------+------+-------------+
|Name                      |Type  |Descritpion  |
+--------------------------+------+-------------+
|bEnableLongTermReference  |bool  |             |
+--------------------------+------+-------------+
|iLTRRefNum                |int   |             |
+--------------------------+------+-------------+





