.. contents:: 
    :local: 

1. Overview
---------------------

this is for openh264 API documentation wiki
    - `ISVCEncoder <wiki/ISVCEncoder>`_
    - `ISVCEncoder <wiki/ISVCDecoder>`_



Notes: to be done
    - `WMEInit` will be replaced with `InitMediaEngine`
    - `WMEUnInit` will be replaced with `UninitMediaEngine` 
   to me done



3. Classes
---------------------

 - `ISVCEncoder <wiki/ISVCEncoder>`_
 - `ISVCDecoder <wiki/ISVCDecoder>`_
 - `Types and Structures <wiki/TypesAndStructures>`_
