.. contents:: 
    :local: 

1. Overview
---------------------

this is for openh264 API documentation wiki
    - `ISVCEncoder <wiki/ISVCEncoder>`_
 
    


Notes: to be done
    - `WMEInit` will be replaced with `InitMediaEngine`
    - `WMEUnInit` will be replaced with `UninitMediaEngine` 
   to me done


2. Basic call flow
---------------------

Here is the basic call flow for video:

3. Classes
---------------------

 - `ISVCEncoder <wiki/ISVCEncoder>`_

