.. contents:: 
    :local:
    :depth: 2


.. _ref-1af450b46a3ff3622f890a12fc16b9a5e0:

ENCODER_OPTION
====================

+-------------------------------------------+-------------+-------------+
|Name                                       |Initializer  |Descritpion  |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_DATAFORMAT                  |= 0          |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_IDR_INTERVAL                |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_SVC_ENCODE_PARAM_BASE       |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_SVC_ENCODE_PARAM_EXT        |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_FRAME_RATE                  |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_BITRATE                     |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_MAX_BITRATE                 |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_INTER_SPATIAL_PRED          |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_RC_MODE                     |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_PADDING_PADDING                    |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_PROFILE                     |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_LEVEL                       |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_NUMBER_REF                  |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_DELIVERY_STATUS             |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_LTR_RECOVERY_REQUEST               |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_LTR_MARKING_FEEDBACK               |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_LTR_MARKING_PERIOD                 |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_LTR                         |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_COMPLEXITY                  |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_ENABLE_SSEI                 |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_ENABLE_PREFIX_NAL_ADDING    |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_ENABLE_SPS_PPS_ID_ADDITION  |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_CURRENT_PATH                |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_DUMP_FILE                   |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_TRACE_LEVEL                 |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_TRACE_CALLBACK              |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_TRACE_CALLBACK_CONTEXT      |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_GET_STATISTICS              |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_STATISTICS_LOG_INTERVAL     |             |             |
+-------------------------------------------+-------------+-------------+
|ENCODER_OPTION_IS_LOSSLESS_LINK            |             |             |
|                                           |             |             |
+-------------------------------------------+-------------+-------------+
